### ISSUE TITLE
Graphical artifact in TitleMenuSeedHashDisplay hack

### ISSUE THREAD

**Issue by Moppu** [Moppu/SecretOfManaRandomizer#21]
See comment in TitleMenuSeedHashDisplay.cs.  Soft resetting sometimes adds some graphical garbage on the file select screen.  Not a big deal and hasn't been observed crashing or otherwise obstructing gameplay - just a weird thing that shows up.

**Comment by Cyb3RGER** [comment]
this can be closed now I guess

**Comment by Moppu** [comment]
Fixed by https://github.com/Moppu/SecretOfManaRandomizer/commit/178a1ae8f9a4c1167ab18f68cfb0576f68ee124f
